url: "https://atotti.github.io" # GitHub Pages URL This Setting is for previewing the site my repository
baseurl: "/tmu-sd-cs.github.io" # GitHub Pages URL This Setting is for previewing the site my repository

title: "東京都立大学 システムデザイン学部 情報科学科 / 東京都立大学大学院 システムデザイン研究科 システムデザイン専攻 情報科学域"
encoding: "utf-8"

# i18n settings
languages: ["ja", "en"]
default_language: "ja"

# Collections
collections:
  ja_news:
    output: true
    permalink: /news/:name.html
  en_news:
    output: true
    permalink: /en/news/:name.html
  ja_staff:
    output: true
    permalink: /staff/:name.html
  en_staff:
    output: true
    permalink: /en/staff/:name.html

# Defaults
defaults:
  # 日本語コンテンツ
  - scope:
      path: "ja/pages"
    values:
      layout: "default"
      lang: "ja"
      permalink: /:basename.html
  - scope:
      path: "ja"
      type: "pages"
    values:
      layout: "default"
      lang: "ja"
      permalink: /:name.html
  - scope:
      path: "ja/news"
    values:
      layout: "default"
      lang: "ja"
  - scope:
      path: "ja/staff"
    values:
      layout: "staff_member"
      lang: "ja"
      permalink: /staff/:basename.html
  - scope:
      path: ""
      type: "ja_news"
    values:
      layout: "default"
      lang: "ja"
  - scope:
      path: ""
      type: "ja_staff"
    values:
      layout: "staff_member"
      lang: "ja"

  # 英語コンテンツ
  - scope:
      path: "en/pages"
    values:
      layout: "default"
      lang: "en"
      permalink: /en/:basename.html
  - scope:
      path: "en"
      type: "pages"
    values:
      layout: "default"
      lang: "en"
      permalink: /en/:name.html
  - scope:
      path: "en/news"
    values:
      layout: "default"
      lang: "en"
  - scope:
      path: "en/staff"
    values:
      layout: "staff_member"
      lang: "en"
      permalink: /en/staff/:basename.html
  - scope:
      path: ""
      type: "en_news"
    values:
      layout: "default"
      lang: "en"
  - scope:
      path: ""
      type: "en_staff"
    values:
      layout: "staff_member"
      lang: "en"
